name: pet_pal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter_native_splash: ^2.4.1
  provider: ^6.1.2
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  firebase_core: ^3.1.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  permission_handler: ^11.3.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  flutter_bkash: ^0.2.0
  firebase_storage: ^12.1.1
  location: ^7.0.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/images/icon.png
  color: "#D9BADC"
  background_image: assets/images/icon.png
  android_12:
    image: assets/images/icon.png
    color: "#D9BADC"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/cats/
    - assets/images/dogs/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
